//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocStorage.Repository.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocStorage.Repository.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not found.
        /// </summary>
        internal static string document_not_found {
            get {
                return ResourceManager.GetString("document_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group with the same name already exists..
        /// </summary>
        internal static string group_already_exists {
            get {
                return ResourceManager.GetString("group_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group already has permission to access this document..
        /// </summary>
        internal static string group_already_exists_in_document_access {
            get {
                return ResourceManager.GetString("group_already_exists_in_document_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group not found.
        /// </summary>
        internal static string group_not_found {
            get {
                return ResourceManager.GetString("group_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected group doesn&apos;t have permission for this document..
        /// </summary>
        internal static string group_not_found_in_document_access {
            get {
                return ResourceManager.GetString("group_not_found_in_document_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with the same username already exists..
        /// </summary>
        internal static string user_already_exists {
            get {
                return ResourceManager.GetString("user_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has permission to access this document..
        /// </summary>
        internal static string user_already_exists_in_document_access {
            get {
                return ResourceManager.GetString("user_already_exists_in_document_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already added to the selected group.
        /// </summary>
        internal static string user_already_in_group {
            get {
                return ResourceManager.GetString("user_already_in_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found in the selected group..
        /// </summary>
        internal static string user_group_not_found {
            get {
                return ResourceManager.GetString("user_group_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected user doesn&apos;t have permission for this document..
        /// </summary>
        internal static string user_not_found_in_document_access {
            get {
                return ResourceManager.GetString("user_not_found_in_document_access", resourceCulture);
            }
        }
    }
}
